#!/bin/sh
## Setup and make sure initramfs is clear
mkdir -p kernel/usr/initramfs
rm -rf kernel/usr/initramfs/*
cp -R ../initramfs_yp-g70/* kernel/usr/initramfs
rm $(find kernel/usr/initramfs -name EMPTY_DIRECTORY -print)
rm -rf $(find kernel/usr/initramfs -name .git -print)

## Build exodus kernel
make exodus_defconfig
#get rid of the damn + after the version
export LOCALVERSION="-EXODUS-R1.1"
make -j4 && cp -a $(find . -name *.ko -print |grep -v initramfs) kernel/usr/initramfs/lib/modules/ && make -j4

## Upload compiled kernel to dropbox
cp arch/arm/boot/zImage ~/Dropbox/Kernel/Compiled/

## flash built kernel with heimdall
# adb shell reboot download
# sleep 5
# heimdall flash --kernel arch/arm/boot/zImage
